### ISSUE TITLE
redirect for password reset?

### ISSUE THREAD

**Issue by cushdan** [BenjaminWFox/nextjs-azureb2c-nextauth#5]
https://github.com/BenjaminWFox/nextjs-azureb2c-nextauth/blob/3aece52e1be50ff8c866708b84e391f6a9c1cf8c/.env.example#L20

any chance you wired up password reset to your signup signin workflow?

Looking into redirecting now from the nextauth callback but would be a great example to add

**Comment by BenjaminWFox** [comment]
I never did wire up the default B2C password reset functionality. It was easier to just hide that link element (using custom page layouts) and create my own link to a password reset user flow.

I didn't find a way with next-auth to handle the way B2C redirected with an "error" state. I made an example PR showing how handling that kind of error might work with a new callback, but it's not fully-baked since it would have required changing some of the conventions next-auth was using.

https://github.com/nextauthjs/next-auth/pull/803

**Comment by cushdan** [comment]
Ok, makes sense. Thanks for the context and suggestion 👍
