### ISSUE TITLE
Get project working with nextjs-auth library

### ISSUE THREAD

**Issue by gregberns** [BenjaminWFox/nextjs-azureb2c-nextauth#7]
Hey Benjamin,

First, thanks for this repo and your work around this area (specifically: https://github.com/nextauthjs/next-auth/issues/1586)

I'm trying to get this repository working with the changes described [here](https://github.com/nextauthjs/next-auth/issues/1586) but am getting this error:

```
AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.
```

Using this configuration in `[...nextauth].js` after updating to `nextjs-auth` version `3.23.0`:
```
Providers.AzureADB2C({
      clientId: clientId, //process.env.AZURE_CLIENT_ID,
      clientSecret: clientSecret, //process.env.AZURE_CLIENT_SECRET,
      scope: 'offline_access User.Read',
      tenantId: tenantGuid, // process.env.AZURE_TENANT_ID,
    })
```

I've looked around, and read through the README and can't find a resolution. 

Have you seen that before? Any thoughts on what changes would need to be made to this project to get it working with the `nextjs-auth` library?

**Comment by BenjaminWFox** [comment]
@gregberns The changes for Azure AD B2C from the PR you linked hasn't made it into a release yet so the current `AzureADB2C` provider still isn't actually Azure AD B2C :( I suspect, since it's a breaking change, it probably won't be included until a v4 release, but that's only my own speculation.

The current configuration I'm using in production is here: https://github.com/nextauthjs/next-auth/issues/468#issuecomment-721441387

I did just test the above with `3.23.2` and it seems to work. Hopefully that helps.

**Comment by gregberns** [comment]
Thanks @BenjaminWFox, that link to the configuration definitely got me past the issue described.

But still seeing issues. I'll keep plugging through it. Thanks for your help.

```
AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.
```

**Comment by BenjaminWFox-Lumedic** [comment]
NIce, glad it helped! For what it's worth, that sounds like something to do with the setup or configuration of the API-related app service.
